spring.application.name=batch
#logging.level.org.springframework.batch=DEBUG
spring.datasource.hikari.maximum-pool-size=30
#
spring.datasource.url=jdbc:postgresql://localhost:5432/mydatabase
spring.datasource.username=myuser
spring.datasource.password=secret
spring.batch.jdbc.initialize-schema=always
spring.threads.virtual.enabled=true